# Generated by Django 5.1.4 on 2025-03-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
    ]
